name: sudoku
description: "A Sudoku game made with Flutter."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version code starts at 50 for installable app, from 3 for instant App
version: 1.0.1+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.1
  firebase_crashlytics: ^4.1.1
  share_plus: ^10.0.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  firebase_messaging: ^15.1.3
  url_launcher: ^6.3.0
  google_play_instant:
    path: ../google_play_instant

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  flutter_gen: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Londrina
      fonts:
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Regular.ttf
          weight: 500
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Light.ttf
          weight: 400
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Thin.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 200
          style: italic